version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rq-worker:
    build: .
    depends_on:
      - redis
    command: rq worker --with-scheduler --url redis://redis:6379/0

  rq-dashboard:
    build: .
    depends_on:
      - redis
    command: rq-dashboard

volumes:
  redis-data: