apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      initContainers:
        - name: rq-worker
          image: python:3.12-slim
          command: ["sh", "-c", "pip install rq && rq worker --with-scheduler --url redis://redis:6379/0"]
          env:
            - name: REDIS_URL
              value: "redis://redis:6379/0"
      containers:
        - name: fastapi
          image: behnambahrami1111/cluster-api-consumer:1.0
          ports:
            - containerPort: 8000
          env:
            - name: HOSTS
              valueFrom:
                configMapKeyRef:
                  name: fastapi-config
                  key: HOSTS
          resources:
            limits:
              cpu: "500m"
              memory: 512Mi