apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: rq-dashboard
spec:
  selector:
    app: rq-dashboard
  ports:
    - protocol: TCP
      port: 9181
      targetPort: 9181
  type: LoadBalancer
