name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        env:
          HOSTS_PATH: ${{ secrets.HOSTS_PATH }}
        run: pytest

      - name: Run ruff
        run: |
          source .env
          ruff check . |
          ruff format .

      - name: Run mypy
        run: mypy .